### ISSUE TITLE
📅 6/18 @ 12:30pm PT - Advanced TypeScript for the future Octokit SDK with @orta

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#29]
💁🏻 **Advanced TypeScript for the future Octokit SDK**
📅 Friday, June 18, 2021
🕐 12:30pm Pacific Time ([in your timezone](https://everytimezone.com/s/e56770c2))
🎙️ with @orta
📍 https://twitch.tv/gregorcodes
🏷️ TypeScript, Octokit

--- 

### Extending constructor options by plugins.

The Octokit SDK is built using a modular plugin architecture. The core package is [`@octokit/core`](https://github.com/octokit/core.js), which can be extended using plugins, e.g. like this

```js
// plugin.js
module.exports = function helloWorldPlugin(octokit, options = { greeting: "Hello" }) => {
  // add a custom method
  return {
    helloWorld: () => console.log(`${options.greeting}, world!`);
  }
};

// index.js
const { Octokit } = require("@octokit/core")
const helloWorldPlugin = require("./plugin")

const MyOctokit = Octokit.plugin(helloWorldPlugin);

const octokit = new MyOctokit({ greeting: "Moin moin" });
octokit.helloWorld(); // logs "Moin moin, world!"
```

The important bit is that typing `octokit.` will suggest both Octokit's core methods such as `octokit.request` and `octokit.graphql`, but also `octokit.helloWorld()`.

But something that is not currently possible is to extend the types the types for Octokit's constructor options so that when I type `new Octokit({` it would suggest `{ greeting }` as an option.

I started a pull request at https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/pull/56 to implement it with Orta.

### Inherit constructor options

Currently Octokit has no required options. But one thing we want to improve is the developer experience to build code for GitHub Enterprise Server or GitHub AE. In order to differentiate between the two we will probably add some kind of `version` parameter that can be set to `api.github.com`, `ghes3.2` or `ghes-3.1-compatible`.

The other reason that we will require constructor options inheritance will be types for the Authentication strategies (see next section).

So given that `version` will be a required parameter, this code should be possible without any type errors

```js
const OctokitGHE31 = Octokit.defaults({ version: 'ghe-3.1' })
const octokit = new OctokitGHE31()
```

### Types for Authentication strategies

I have a long standing open issue for this one: https://github.com/octokit/core.js/issues/323

Basically what I want a better developer experience when using authentication strategies such as [`@octokit/auth-app`](https://github.com/octokit/auth-app.js/)

```js
import { Octokit } from "@octokit/core";
import { createAppAuth } from "@octokit/auth-app"
const octokit = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    // should provide IntelliSense for createAppAuth options:
    // https://github.com/octokit/auth-app.js/#createappauthoptions-or-new-octokit-auth-
  }
})
```

This should work together with the inheritence of options types from `Octokit.defaults()` so this will be possible

```js
import { Octokit } from "@octokit/core";
import { createAppAuth } from "@octokit/auth-app"

const AppOctokit = Octokit.defaults({
  authStrategy: createAppAuth
})

const octokit = new AppOctokit({
  auth: {
    // should provide IntelliSense for createAppAuth options:
    // https://github.com/octokit/auth-app.js/#createappauthoptions-or-new-octokit-auth-
  }
})
```

#### Outline

1. The TypeScript for today's @octokit and where it falls short
2. Make Types extendable by plugins (gr2m/javascript-plugin-architecture-with-typescript-definitions#56)
3. Remember default options set with `Octokit.defaults()`

#### Preparation

- [x] Prepare https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions for the show: 
  - [x] rewrite it JavaScript as native ES Module with separated Type definitions in `index.d.ts`
  - [x] Prepare questions to work through with @orta during the show
- [x]  30 minute announcement tweet
- [x]  start of show tweet
- [ ]  comment on issue
- [ ]  recording available tweet

<a name="recording"></a>
#### Recording

_will be added after the show_

<a name="shownotes"></a>
#### Shownotes

- We used the code example show at https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-plugin-d-ts.html to make the type merging work for `Base.options` defined in plugins.
- Playground for the AuthStrategy/Auth options types problem we couldn't figure out in the end: [TypeScript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggrsAFgZWAJwIbAgcxDAOwBMB5MYASwHsCBnAHgCgpYEV0tcQoIAPbYrSgAKKuWp0AXFAwEQASigBeAHwy5ykWMo1a02QuVqDjNUqgBvZjLapM2PNPhI7nPAG5rGNtIAKGTABbCGw0Bmd2ey4VAG0ABgBdTwBfT0YAY11gKGAAdyoAMRhNYTBEGghpAjhAgCMINEVVS1TGRgB6dqgARTgIWh0CaVzEbgohJGhQSCgAMyo0HMRobyQobQkoAAMDLYB+KAB1UahxggBybMmc8Gh5xeudti318RpTglmGiCI5tCpAktoE8XBwHCAXhsaBksjYkDAnLYwVxCKQ3nRNFYWKtENILMkADReJFRRw5fJFImpIA)
- TS Playground asking the community how to solve the issue inferring the generic type https://twitter.com/gr2m/status/1405998002674700289
- A solution proposal from the TS community: https://twitter.com/gr2m/status/1406037504164204547

**Comment by gr2m** [comment]
Video is now available on Twitch:
https://www.twitch.tv/videos/1060393045

**Comment by oscard0m** [comment]
Linking these tweets following up the show:
* TS Playground asking the community how to solve the issue inferring the generic type https://twitter.com/gr2m/status/1405998002674700289
* A solution proposal from the TS community: https://twitter.com/gr2m/status/1406037504164204547
