### ISSUE TITLE
Very new and in need of mentorship and guidance

### ISSUE THREAD

**Issue by johnjsatter** [gr2m/helpdesk#37]
hello-world, I am continuing to learn and engage and so grateful and happy to be expanding my community. However, I do lack some basic foundational knowledge and am reaching out to ask for help.

I want to make sure first and foremost that I handle any safety concerns pertaining to my local network.

Any ideas on where and whom to maybe reach out to first for mentor ship? all ideas welcome

**Comment by gr2m** [comment]
Hi @johnjsatter, during normal times I'd recommend to look for local tech meetups and meet people in person, it's rather hard to find mentors remotely, albeit not impossible. 

I don't have any experience in network security myself, so I can't help you I'm afraid :(

Maybe try to find like-minded folks with more experience on Twitter and https://dev.to/ and connect with them?
