### ISSUE TITLE
📅 4/26 @ 5pm PT - Create a `cowsay` GitHub Action with JavaScript

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#4]
💁🏻 **GitHub Enterprise repository auditing**
📅 April 29, 2021
🕐 5pm Pacific Time ([in your timezone](https://everytimezone.com/s/3d9bcef2))
🎙️ no guests
🏷️ Action

--- 

The goal is to create a GitHub Action with JavaScript from scratch and to publish it to GitHub's marketplace.

#### Outline

1. Create a new repository based on [gr2m/hello-world-js-action](https://github.com/gr2m/hello-world-js-action)
2. Update all mentions of `hello-world-js-action` to `cowsay-action`
3. Install the [`cowsay`](https://github.com/piuccio/cowsay) package
4. Update the tests
5. Publish to GitHub Marketplace

**Comment by gr2m** [comment]
Going live right now at https://www.twitch.tv/gregorcodes

**Comment by gr2m** [comment]
We are done!

The repository: https://github.com/gr2m/cowsay-action
The action on marketplace: https://github.com/marketplace/actions/cowsay-js

Here is the recording on twitch: https://www.twitch.tv/gregorcodes/video/1002124938

<a href="https://www.twitch.tv/gregorcodes/video/1002124938"><img width="861" alt="image" src="https://user-images.githubusercontent.com/39992/116167914-2df19d80-a6b6-11eb-8232-6464d8f1a768.png"></a>

Feel free to ask any questions you have about the stream!

**Comment by oscard0m** [comment]
Nice session once again. Super useful to consolidate and discover some concepts not clear to me 😄 

---
I didn't know about:
- [GitHub Actions branding](https://github.com/haya14busa/github-action-brandings)
- [@vercel/ncc](https://github.com/vercel/ncc)

Some small research inspired by this video:
- [GitHub issue with more details](https://github.com/actions/runner/issues/772#issuecomment-754883065) on why GitHub Actions are not supporting node14 yet
- GitHub Actions in JS do not support `require` / `import` files. This only applies to `node_modules` but for regular relative paths it works right? I have seen examples working.

**Comment by gr2m** [comment]
Thank you for adding the links, much appreciated!
