### ISSUE TITLE
📅 4/27 @ 11:30 PT - Octokit automation: OpenAPI

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#5]
💁🏻 **Octokit automation: OpenAPI**
📅 April 27, 2021
🕐 11:30am Pacific Time
🎙️ no guests
🏷️ Action, OpenAPI, Octokit, Automation

--- 

In this show, I'm walking through the automation process triggered by a new release of [GitHub's official OpenAPI spec](https://github.com/github/rest-api-description/).

The recording can be found here: https://www.twitch.tv/videos/1002874596

<a href="https://www.twitch.tv/videos/1002874596"><img width="1338" alt="Screenshot of video hosted on twitch.tv/gregorcodes" src="https://user-images.githubusercontent.com/39992/116297879-9db46680-a750-11eb-8eb7-445c50a5157b.png"></a>

**Comment by gr2m** [comment]
The show is now archived on youtube, too: https://youtu.be/xDTHbL5qcvQ.

**Comment by oscard0m** [comment]
Great session @gr2m . I really enjoyed and liked to follow all the journey 🤖 . It's AMAZING the ecosystem of GitHub Actions you created. 

---

Here I leave you some feedback or thoughts about this session:
- **Did you consider to productize this solution somehow so it is one-click alternative to `dependabot` or `renovatebot` ?**
- https://github.com/apps/octokit-release-notifier url works but I'm not finding it when using search box in https://github.com/apps/. Is this something to report to GitHub?
- Is the code associated to the GitHub App public? https://github.com/gr2m/release-notifier-action. I would like to see the logic applied here.
- ℹ️  For the ones interested in the GitHub App to tackle semantic commit messages for PRs with one commit (mentioned in the video), you can follow up squash-commit-app

---

> Do you want to talk about automation?

Yes yes yes yes yes yes

**Comment by gr2m** [comment]
> Did you consider to productize this solution somehow so it is one-click alternative to `dependabot` or `renovatebot`

I've been in that business before with https://greenkeeper.io/, I'm not interested to get into it again 😄 

> https://github.com/apps/octokit-release-notifier url works but I'm not finding it when using search box in https://github.com/apps/. Is this something to report to GitHub?

I didn't publish the app in the marketplace, that's why you cannot find it. I could, but I think it's to specialized.

> Is the code associated to the GitHub App public? https://github.com/gr2m/release-notifier-action. I would like to see the logic applied here.

There is no code, that's the beauty of it. A GitHub App registration such as https://github.com/apps/octokit-release-notifier is just a means of authentication. I pass the app's ID and a private key to https://github.com/gr2m/release-notifier-action, and then the action code is iterating through all repositories that the `octokit-release-notifier` app is installed on and creates the repository dispatch event.

> ℹ️  For the ones interested in the GitHub App to tackle semantic commit messages for PRs with one commit (mentioned in the video), you can follow up squash-commit-app

Oh yes, when are we going to build https://github.com/gr2m/squash-commit-app @oscard0m?

**Comment by oscard0m** [comment]
> There is no code, that's the beauty of it. A GitHub App registration such as https://github.com/apps/octokit-release-notifier is just a means of authentication. I pass the app's ID and a private key to https://github.com/gr2m/release-notifier-action, and then the action code is iterating through all repositories that the `octokit-release-notifier` app is installed on and creates the repository dispatch event.

Ok. I was missing the flow on [this part](https://github.com/gr2m/release-notifier-action/blob/d1a9679a309dcedca58be019a9f48e34ba55dd7c/index.js#L26). It's a very smart solution.

**Comment by oscard0m** [comment]
> > There is no code, that's the beauty of it. A GitHub App registration such as https://github.com/apps/octokit-release-notifier is just a means of authentication. I pass the app's ID and a private key to https://github.com/gr2m/release-notifier-action, and then the action code is iterating through all repositories that the `octokit-release-notifier` app is installed on and creates the repository dispatch event.
> 

Ok. I was missing the flow on [this part](https://github.com/gr2m/release-notifier-action/blob/d1a9679a309dcedca58be019a9f48e34ba55dd7c/index.js#L26). It's a very smart solution.

> Oh yes, when are we going to build https://github.com/gr2m/squash-commit-app @oscard0m?

I think I will take it next week. I want to cath up with all the stuff I have open and this should be a quick win.
