### ISSUE TITLE
Regarding the Github

### ISSUE THREAD

**Issue by thehawkop** [gr2m/helpdesk#50]
Hii tanvi here,
I have recently joined Github and I don't know how to run this application, I just know that its an app for software development and many things. Abruptly I saw your profile, I thought to seek help from you. So my question is how to use this application as a coder or software developer.

**Comment by gr2m** [comment]
You mean GitHub? It's not an application you run, it's a website. You don't really use it for the coding part of software development, but for hosting the code and for collaboration. 

I'd recommend to read through the docs at https://docs.github.com/en and for general questions you can ask at https://github.community/, I hope that helps?
