### ISSUE TITLE
octokit-plugin-create-pull-request force appends "repos" into url

### ISSUE THREAD

**Issue by samusiu** [gr2m/helpdesk#65]
### Please avoid duplicates

- [X] I checked [all past ideas and shows](https://github.com/gr2m/helpdesk/issues?q=is%3Aissue) and none of them matched my idea.

### Description

Hi, I'm kind of new to front end and have been trying to use octokit-plugin-create-pull-request to create PRs, however, the request fails because the logic hard codes "repos" into the url when my github url doesn't include it. FYI I'm using an enterprise github so I've replaced the actual owner and repo names with dummies. 
For example, for this request,

```octokit
      .createPullRequest({
        owner: "sam",
        repo: "testrepo",
        title: "test github api",
        body: "test github api",
        head: "test github api PR",
        base: "main"
 ```
 I get this error
```
       GET https://github.com/repos/sam/testrepo net::ERR_FAILED
```
because my actual url would be `https://github.com/sam/testrepo`
Is it possible to not add that "repos" into the url? 

Thank you!

### Would you be interested in joining the show?

- [ ] yes

**Comment by gr2m** [comment]
it would be better to open an issue on https://github.com/gr2m/octokit-plugin-create-pull-request if you found a bug.

In this case, the `/repos` part is correct, because this is how the API work. This repo's public URL is https://github.com/gr2m/helpdesk. But the API endpoint is https://api.github.com/repos/gr2m/helpdesk

**Comment by samusiu** [comment]
ahh yeah I realized that, looks like the request is just failing elsewhere. Sorry for the inconvenience! I'm still getting familiar with the API

**Comment by gr2m** [comment]
no problem, good luck!
