### ISSUE TITLE
📅 5/6 @ 1pm PT - Script Kit meets Octokit with @johnlindquist

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#8]
💁🏻 **[Script Kit](https://www.scriptkit.com/) meets @Octokit**
📅 Monday, May 6rd, 2021
🕐 1pm US Pacific Time ([in your timezone](https://everytimezone.com/s/296a4f21))
🎙️ with @johnlindquist
🏷️ Script, Automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Script Kit meets Octokit

>> happy to do a live coding show :) Want to join in? I built [johnlindquist/kit#221](https://github.com/johnlindquist/kit/discussions/221) for now, but I'd love to hook it up with [@octoherd](https://github.com/octoherd), so you could run any existing Octoherd Script with `kit`, and get the prompts using your sweat UI!
>
> Let's do it

— @johnlindquist [on twitter](https://mobile.twitter.com/johnlindquist/status/1388243300365213696)

**Update**: `kit` does currently not support importing ES Modules, so we will postpone that idea for now. We will instead create a `kit` script using @octokit

#### Outline

- Introductions, what is [Script Kit](https://www.scriptkit.com/)
- Use GitHub's API from Kit, persist the GitHub token
- Use Octokit from Kit
  - Import Octokit
  - Import TypeScript definitions
  - create a new repository issue
- Attempt to use an @octoherd script from Kit
  - esm import workaround
  - Try to use https://github.com/octoherd/script-star-or-unstar from Kit

<a name="recording"></a>
#### Recording

- YouTube: https://youtu.be/aSjHCTKuJOc

<a name="shownotes"></a>
#### Shownotes

- [scriptkit.com](https://www.scriptkit.com/)
- [`scriptkit-octokit`](https://github.com/gr2m/scriptkit-octokit/) - The Octokit SDK for Script Kit
- The two scripts we published: https://github.com/johnlindquist/kit/discussions/246

#### Preparation

- [x] Build a minimal `kit` example that uses @octokit
- [x] create an Outline for the show
- [x] confirm outline with @johnlindquist

**Comment by gr2m** [comment]
`kit` does currently not support importing ES Modules, so we will postpone that idea for now. We will instead create a `kit` script using @octokit

**Comment by johnlindquist** [comment]
To be clear, kit supports esm. The "npm" auto-installer/importer is a WIP for esm.

You can import esm modules in your scripts with the standard js import keyword or the "await import" function.

**Comment by gr2m** [comment]
sorry that I stated that incorrectly, thanks for the correction 👍🏼

**Comment by gr2m** [comment]
Aaand we are going live at twitch.tv/gregorcodes

**Comment by gr2m** [comment]
The video is now on Twitch: https://www.twitch.tv/videos/1013528810

<a href="https://www.twitch.tv/videos/1013528810"><img width="1342" alt="image" src="https://user-images.githubusercontent.com/39992/117367414-013c4380-ae77-11eb-8bbf-0efd1acb5d24.png"></a>

**Comment by gr2m** [comment]
I added some [shownotes](https://github.com/gr2m/helpdesk/issues/8#shownotes) to the issue description

**Comment by gr2m** [comment]
Video is now archived on YouTube: https://youtu.be/aSjHCTKuJOc

Feel free to keep asking questions, but I'm going to close the issue as the show is done
